<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2001, 2012, Oracle and/or its affiliates. All rights reserved.
  ~ Oracle and Java are registered trademarks of Oracle and/or its
  ~ affiliates. Other names may be trademarks of their respective owners.
  ~ UNIX is a registered trademark of The Open Group.
  ~
  ~ This software and related documentation are provided under a license
  ~ agreement containing restrictions on use and disclosure and are
  ~ protected by intellectual property laws. Except as expressly permitted
  ~ in your license agreement or allowed by law, you may not use, copy,
  ~ reproduce, translate, broadcast, modify, license, transmit, distribute,
  ~ exhibit, perform, publish, or display any part, in any form, or by any
  ~ means. Reverse engineering, disassembly, or decompilation of this
  ~ software, unless required by law for interoperability, is prohibited.
  ~ The information contained herein is subject to change without notice
  ~ and is not warranted to be error-free. If you find any errors, please
  ~ report them to us in writing.
  ~ U.S. GOVERNMENT END USERS: Oracle programs, including any operating
  ~ system, integrated software, any programs installed on the hardware,
  ~ and/or documentation, delivered to U.S. Government end users are
  ~ "commercial computer software" pursuant to the applicable Federal
  ~ Acquisition Regulation and agency-specific supplemental regulations.
  ~ As such, use, duplication, disclosure, modification, and adaptation
  ~ of the programs, including any operating system, integrated software,
  ~ any programs installed on the hardware, and/or documentation, shall be
  ~ subject to license terms and license restrictions applicable to the
  ~ programs. No other rights are granted to the U.S. Government.
  ~ This software or hardware is developed for general use in a variety
  ~ of information management applications. It is not developed or
  ~ intended for use in any inherently dangerous applications, including
  ~ applications that may create a risk of personal injury. If you use
  ~ this software or hardware in dangerous applications, then you shall
  ~ be responsible to take all appropriate fail-safe, backup, redundancy,
  ~ and other measures to ensure its safe use. Oracle Corporation and its
  ~ affiliates disclaim any liability for any damages caused by use of this
  ~ software or hardware in dangerous applications.
  ~ This software or hardware and documentation may provide access to or
  ~ information on content, products, and services from third parties.
  ~ Oracle Corporation and its affiliates are not responsible for and
  ~ expressly disclaim all warranties of any kind with respect to
  ~ third-party content, products, and services. Oracle Corporation and
  ~ its affiliates will not be responsible for any loss, costs, or damages
  ~ incurred due to your access to or use of third-party content, products,
  ~ or services.
  -->

<!DOCTYPE app-descriptor [
  <!ELEMENT app-descriptor ( dir-structure+, copy-pattern+ ) >
  <!ATTLIST app-descriptor
    update (true|false) #IMPLIED
    id CDATA #IMPLIED
    default-name CDATA #IMPLIED
  >

  <!ELEMENT dir-structure ( dir+ ) >

  <!ELEMENT dir ( #PCDATA ) >
  <!ATTLIST dir
    primary (true|false) #IMPLIED
    platform (win|unix) #IMPLIED
  >

  <!ELEMENT copy-pattern ( copy+ ) >
  <!ATTLIST copy-pattern src-root CDATA #REQUIRED >

  <!ELEMENT copy ( src-dir, src-file, dest-dir ) >
  <!ATTLIST copy
    clear-dest-dir (true|false) #IMPLIED
    recursive (true|false) #IMPLIED
    preserve-subdirs (true|false) #IMPLIED
    filter-files (true|false) #IMPLIED
    mode CDATA #IMPLIED
    primary (true|false) #IMPLIED
    platform (win|unix) #IMPLIED
    endeca-version (460|470|480|500) #IMPLIED
  >

  <!ELEMENT dest-dir ( #PCDATA ) >
  <!ELEMENT src-dir ( #PCDATA ) >
  <!ELEMENT src-file ( #PCDATA ) >
]>
<app-descriptor update="true" id="DefaultTemplateManagerApp" default-name="Discover">

  <dir-structure>
    <dir>data/state</dir>
  </dir-structure>

  <copy-pattern src-root=".">
    <copy filter-files="true" clear-dest-dir="true">
      <src-dir>./pipeline</src-dir>
      <src-file>*</src-file>
      <dest-dir>./config/pipeline</dest-dir>
    </copy>
  </copy-pattern>
  
  <copy-pattern src-root=".">
    <copy filter-files="true" clear-dest-dir="true" preserve-subdirs="true" recursive="true" filter-files="true">
      <src-dir>./ifcr</src-dir>
      <src-file>*</src-file>
      <dest-dir>./config/ifcr</dest-dir>
    </copy>
  </copy-pattern>

  <copy-pattern src-root="." >
    <copy clear-dest-dir="true" preserve-subdirs="true" recursive="true" filter-files="true">
      <src-dir>./editors_config</src-dir>
      <src-file>*</src-file>
      <dest-dir>./config/editors_config</dest-dir>
    </copy>
  </copy-pattern>

  <copy-pattern src-root=".">
    <copy clear-dest-dir="true" recursive="true" preserve-subdirs="true" filter-files="true">
      <src-dir>./cartridge_templates</src-dir>
      <src-file>*</src-file>
      <dest-dir>./config/cartridge_templates</dest-dir>
    </copy>
  </copy-pattern>
    
  <copy-pattern src-root=".">
    <copy clear-dest-dir="false" recursive="true" preserve-subdirs="true" platform="win" filter-files="true">
      <src-dir>./control</src-dir>
      <src-file>*.bat</src-file>
      <dest-dir>./control</dest-dir>
    </copy>
  </copy-pattern>
  
  <copy-pattern src-root=".">
    <copy clear-dest-dir="false" recursive="true" preserve-subdirs="true" platform="unix" mode="755" filter-files="true">
      <src-dir>./control</src-dir>
      <src-file>*.sh</src-file>
      <dest-dir>./control</dest-dir>
    </copy>
  </copy-pattern>
  
  <copy-pattern src-root=".">
    <copy clear-dest-dir="true">
      <src-dir>./test_data/baseline</src-dir>
      <src-file>*</src-file>
      <dest-dir>./test_data/baseline</dest-dir>
    </copy>
  </copy-pattern>

  <copy-pattern src-root=".">
    <copy clear-dest-dir="true" filter-files="true">
      <src-dir>./state</src-dir>
      <src-file>autogen_dimensions.xml</src-file>
      <dest-dir>./data/state</dest-dir>
    </copy>
  </copy-pattern>

  <copy-pattern src-root=".">
    <copy preserve-subdirs="true" recursive="true">
      <src-dir>./binary_files/</src-dir>
      <src-file>*</src-file>
      <dest-dir>./config/media</dest-dir>
    </copy>
  </copy-pattern>

</app-descriptor>

